### ISSUE TITLE
Problème de label avec fonction et boucles imbriquées

### ISSUE THREAD

**Issue by rvende** [rvende/compilateur#1]
Problème : génère un "jump l2" mais ce label n'est pas définit ailleurs, l4 pas définit passe directement à l5 idem pour l9 passe directement à l10
code :
function somme(n,m,k){ 
	if(n<=0){ 
		return 2+m+k;  
	}else{ 
		if(n == 15){ 
			return n;
		} 
		var i; 
		for(i =0;i<3;i=i+1){ 
			n = n-1; 
			if(n == 12){ 
				break;
		 	}
		} 
		return n*m+k + somme(n-1,m,k-1) + k -2; 
	} 
} 
function main() { 
	var a; 
	a = 2; 
	a = a+ somme(22,4,2); 
	return a;
}

**Comment by WarrenWeber** [comment]
Problème résolu avec le commit 7cc1451.
